name: Selenium Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          wget -q "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip

      - name: Kill existing Chrome instances
        run: pkill -9 chrome || true


    #      - name: Set Up Selenium WebDriver
#        run: echo "Selenium WebDriver is set up."

      - name: Run Selenium Tests
        run: mvn test


      - name: Run Selenium Tests
        run: mvn test
        continue-on-error: true  # Ensure workflow continues to send email even on failure

      - name: Send Email Notification
        if: always()  # Run this step regardless of test result (success or failure)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_EMAIL }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Selenium Test Results - ${{ github.workflow }} (Run #${{ github.run_number }})"
          to: "etornam.koko@amalitech.com"
          from: "GitHub Actions <${{ secrets.SMTP_EMAIL }}>"
          body: |
            **Repository**: ${{ github.repository }}
            **Branch**: ${{ github.ref }}
            **Commit**: ${{ github.sha }}
            **Status**: ${{ job.status }}

            Check full logs here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}